### ISSUE TITLE
No such file or directory at ./main.pl line 10, <STDIN> line 1.

### ISSUE THREAD

**Issue by ConceptzX** [hudson-newey/autogpt-jailbreak#1]
Getting this error message. any suggestions?

**PS E:\AutoGPT> perl ./main.pl ~/AutoGPT
Using AutoGPT after this script has been applied may lead to damage or harm to your computer
The author takes no responsability for any damage or harm caused by the use of this script
Are you sure you want to continue (yes/no)? (no)
yes
Removing workspace restrictions...
No such file or directory at ./main.pl line 10, <STDIN> line 1.**

**Comment by hudson-newey** [comment]
I've fixed the script

However, i'm marking this project as deprecated because AutoGPT now provides all the benefit you'd get from this script through an env variable (`RESTRICT_TO_WORKSPACE=False`)

The script used to just remove these exceptions
[https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/autogpt/autogpt/workspace/workspace.py#L127-L135](https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/autogpt/autogpt/workspace/workspace.py#L127-L135)
[https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/autogpt/autogpt/workspace/workspace.py#L141-L144](https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/autogpt/autogpt/workspace/workspace.py#L141-L144)

So another fix would be to just comment these lines out

---

Additionally: I see that you're trying to run AutoGPT unrestricted from your `E:` drive. I would not recommend this as this script (and any above options) allows AutoGPT to delete system32 (the windows equivalent of `rm -rf /` example in the docs).

I'd **highly** recommend that if you're going to remove workspace restrictions (either through the script, env variable, or manual code changes), that run your AutoGPT agent from a [Docker](https://www.docker.com/) container.
